#!/usr/bin/env bash
# install nginx --> engine x
sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
