#!/usr/bin/env bash
#
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html
sudo service nginx start
sudo chmod 777 /etc/nginx/sites-available/
sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
