#!/usr/bin/env bash
# blocks access to Facebook and localhost loopback by changing hosts file
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost$/127.0.0.2 localhost/' ~/hosts.new
grep -q 'facebook.com' ~/hosts.new &&
 sed -i 's/.*facebook.com$/8.8.8.8 facebook.com/' ~/hosts.new ||
 echo '8.8.8.8 facebook.com' >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
